### PR TITLE
Added code of C++

### PR DESCRIPTION
**Pull request by khushimarothi**
I have added some medium level leetcode question in c++ folder.
please assign hactoberfest labels.

### CODE REVIEW

**Comment by AdarshAddee** [comment]
I appreciate your work. You are really a good programmer. As your programs are half coded which makes users to read and understand it. Please make sure that you are implementing these classes in your code so that other can under easily and don't forget to mention your name in your file as a comment.

Waiting for your PR!!!

**Comment by khushimarothi** [comment]
@AdarshAddee they are the solution of leet code questions so they were that way since it only allows you to code the solution function itself. I also embedded the link of leetcode so that the one reading it can redirect there and can get better understanding. 
 But will try to implement it that way to . :)

**Comment by AdarshAddee** [comment]
That's Perfect. Waiting for your PR!!!

**Comment by khushimarothi** [comment]
Repo shows excluded on my hacktoberfest profile what to do?

**Pull request merged**
