### PR TITLE
InnocentDaksh63

### PR DESCRIPTION
**Pull request by InnocentDaksh63**

### CODE REVIEW

**Comment by AdarshAddee** [comment]
This is not the right way. Please make sure you have merged pull request in right way. Please read rules carefully. Enter names in CONTRIBUTORS.md file when you have contributed.

Waiting for PR!!!

**Comment by AdarshAddee** [comment]
Hello sir, Kindly make another PR for contributors.md file. Sorry for inconvenient!

Waiting for your PR!!!

**Comment by AdarshAddee** [comment]
I have successfully added your name and details in CONTRIBUTORS.md file as you are the contributor of this repo.

Thank you for participating!!!

**Comment by InnocentDaksh63** [comment]
ohk i commit it by using proper guidelines

**Pull request closed without merging**
